name: build cross platform
on: 
  push:
  pull_request:
jobs:
  xgo:
    name: xgo
    strategy:
      matrix:
        go_version:
          - 1.13.x
        os:
          - windows
          - linux
          - darwin
        arch:
          - amd64
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Golang CGO cross compiler
      uses: crazy-max/ghaction-xgo@v0.4.0
      with:
        go_version: ${{ matrix.go_version }}
        dest: build
        targets: ${{ matrix.os }}/${{ matrix.arch }}
        v: false
        x: false
        ldflags: -s -w
    - name: upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: binary ${{ matrix.go_version }} ${{ matrix.os }} ${{ matrix.arch }}
        path: build/github.com/fleaz
