name: build-xgo
on: 
  push:
  pull_request:
jobs:
  xgo:
    name: Build cross platform
    strategy:
      matrix:
        go_version:
          - 1.12.4
          - 1.13.x
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Golang CGO cross compiler
      uses: crazy-max/ghaction-xgo@v0.4.0
      with:
        go_version: ${{ matrix.go_version }}
        dest: build
        targets: windows/amd64,linux/amd64,darwin/amd64
        v: true
        x: true
        ldflags: -s -w

